javascript carousel
Adam-SungMin-Park/c1120-code-solutions pull request #64
Opened 2020-12-10 21:10 UTC by Adam-SungMin-Park

![Screen Shot 2020-12-10 at 13 10 16](https://user-images.githubusercontent.com/57808972/101830234-0f18b300-3ae9-11eb-86d6-6638c87ad7e2.png)

2020-12-10 21:25 UTC, uzair-ashraf requested changes

2020-12-10 21:25 UTC, uzair-ashraf commented on javascript-carousel/main.js
> +    $circle1.className = "far fa-circle"
This kind of repeating logic was the reason for loops were created, please refactor with a for loop.

2020-12-10 21:25 UTC, uzair-ashraf commented on javascript-carousel/main.js
> +interval = window.setInterval(imageChange,3000);
![image](https://user-images.githubusercontent.com/52118958/101831639-0f19b280-3aeb-11eb-8e9c-98c3e6035a41.png)

When the user hasn't clicked for 2 seconds, and then clicks, then one second later the image will change again, you need something to reset the interval if the user clicks.

2020-12-14 01:39 UTC, Adam-SungMin-Park commented on javascript-carousel/main.js
> +    $circle1.className = "far fa-circle"
updated

2020-12-14 01:39 UTC, Adam-SungMin-Park commented on javascript-carousel/main.js
> +interval = window.setInterval(imageChange,3000);
updated

2020-12-14 23:54 UTC, Zhiwutian approved these changes
👍

2020-12-14 23:54 UTC, merged